modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="dt" #mandatory
version="1.16.5-1.0" #mandatory
displayName="DataTool" #mandatory
authors="yuo" #optional
description='''
Data Tool.
'''
[[dependencies.dt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
